using System;
using UnityEngine;
using UnityEngine.UI;

public class CardScript : MonoBehaviour
{
    public bool doneGeneratingColors = false;
    bool changeColorToGrey;
    public float timeLeft;
    public float restartTime;
    public Color generatedColor;
    public  Color globalGeneratedColor;
    public bool generatedColorSuccessfully; //represents if a valid color was generated
    public Text gameInformation;
    public Canvas canvas;
    public bool cardColorGenerated;
    public bool CardColorIsVerified;
    void Start()
    {
        CardColorIsVerified = true;
        cardColorGenerated = false;
        changeColorToGrey = false;
        if (restartTime == 0)
        {
            restartTime = 5;
        }
        timeLeft = restartTime;
        generatedColorSuccessfully = false;
        canvas = GameObject.Find("Canvas").GetComponent<Canvas>();
        GetComponent<Renderer>().material.color = GenerateColor.CreateColor();
        try
        {
            gameInformation = canvas.transform.Find("GameInfo").GetComponent<Text>();
            gameInformation.text = "Use your character to match the colors.\n Memorize the colors before they turn to grey. \n Get ready.";
        }
        catch (Exception ex)
        {

        }
    }
    public Color GetGeneratedColor()
    {
        return globalGeneratedColor;
    }

    void Update()
    {
        stopWatch();
        ////Debug.Log("Color: "+generatedColor);
        if (changeColorToGrey == true)
        {
            GetComponent<Renderer>().material.color = Color.grey; //generate the color grey and save the color to the cube
            
            doneGeneratingColors = true;
        }
        else if (changeColorToGrey == false)
        {
            //GetComponent<Renderer>().material.color = GenerateColor.color; //generate a random color and save the color to the cube

            generatedColor = GetComponent<Renderer>().material.color; //this code saves the color that was generated by the script
            globalGeneratedColor = generatedColor;
        }
    }

    public void stopWatch() //functions like a stopwatch and tells the player when the game starts
    {
        timeLeft -= Time.deltaTime;
        if (timeLeft <= 0 && changeColorToGrey==false)
        {
            if (generatedColor == Color.red)
            {
                transform.gameObject.tag = "Red1";
                generatedColorSuccessfully = true;
                GenerateColor.colors.Add(generatedColor);
            }
            else if (generatedColor == Color.blue)
            {
                transform.gameObject.tag = "Blue1";
                generatedColorSuccessfully = true;
                GenerateColor.colors.Add(generatedColor);
            }
            else if (generatedColor == Color.green)
            {
                transform.gameObject.tag = "Green1";
                generatedColorSuccessfully = true;
                GenerateColor.colors.Add(generatedColor);
            }
            // else if (generatedColor == Color.yellow)
            // {
            //     transform.gameObject.tag = "Yellow1";
            //     generatedColorSuccessfully = true;
            //     GenerateColor.colors.Add(generatedColor);
            // }
            else
            {
                generatedColorSuccessfully = false;
                //Debug.Log(generatedColor);
            }
            if (generatedColorSuccessfully == false) //if a valid color was generated, then change the color to grey or restart the stopwatch if not
            {
                changeColorToGrey = false;
                timeLeft = restartTime;
                //Debug.Log("Restart the stopwatch");
                GetComponent<Renderer>().material.color = GenerateColor.CreateColor();
            }
            else
            {
                changeColorToGrey = true;
                //Debug.Log("Color should change to grey");
                try
                {
                    cardColorGenerated = true;
                }
                catch (Exception ex)
                {

                }

            }
        }
    }
}






// using System.Diagnostics;
// using UnityEngine;

// public class CardScript : MonoBehaviour
// {
//     bool changeColor;
//     public float timeLeft;
//     public float restartTime;
//     // Start is called once before the first execution of Update after the MonoBehaviour is created
//     void Start()
//     {

//         changeColor = true;
//         if (restartTime == 0)
//         {
//             restartTime = 5;
//         }
//         timeLeft = restartTime;
//     }

//     // Update is called once per frame
//     void Update()
//     {
//         stopWatch();
//         if (changeColor == false)
//         {
//             GetComponent<Renderer>().material.color = Color.grey;
//         }
//         else
//         {
//             GetComponent<Renderer>().material.color = GenerateColor.color;

//         }
//     }
//     public void stopWatch()
//     {
//         timeLeft -= Time.deltaTime;
//         if (timeLeft <= 0)
//         {
//             timeLeft = restartTime;
//             changeColor = false;
//         }
//     }
// }
